# Generated by Django 5.2.7 on 2026-01-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True, help_text='Foreign key to Spring Boot project table', unique=True)),
                ('semantic_text', models.TextField(blank=True, help_text='Reduced semantic representation')),
                ('embedding', models.JSONField(default=list, help_text='768-dim embedding vector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_embeddings',
                'indexes': [models.Index(fields=['project_id'], name='project_emb_project_43e9cd_idx')],
            },
        ),
    ]
