# Generated by Django 5.2.7 on 2026-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True, help_text='Foreign key to Spring Boot project table', unique=True)),
                ('project_json', models.JSONField(default=dict, help_text='Canonical project JSON payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_json_store',
                'indexes': [models.Index(fields=['project_id'], name='project_jso_project_c0530d_idx')],
            },
        ),
    ]
