# Generated by Django 5.2.7 on 2026-01-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_id', models.CharField(db_index=True, max_length=64)),
                ('ratee_id', models.CharField(db_index=True, max_length=64)),
                ('project_id', models.CharField(db_index=True, max_length=64)),
                ('category_scores', models.JSONField(default=dict)),
                ('raw_rating', models.FloatField()),
                ('adjusted_rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ratings',
                'indexes': [models.Index(fields=['ratee_id'], name='ratings_ratee_i_f53feb_idx'), models.Index(fields=['rater_id'], name='ratings_rater_i_8e9aab_idx'), models.Index(fields=['project_id'], name='ratings_project_e022d1_idx')],
            },
        ),
    ]
