# Generated by Django 5.2.7 on 2025-12-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='semantic_text',
            field=models.TextField(blank=True),
        ),
    ]
