# Generated by Django 5.2.7 on 2026-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.IntegerField(db_index=True, help_text='Foreign key to Spring Boot resume table', unique=True)),
                ('resume_json', models.JSONField(default=dict, help_text='Canonical resume JSON payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resume_json_store',
                'indexes': [models.Index(fields=['resume_id'], name='resume_json_resume__1bd71d_idx')],
            },
        ),
    ]
